### ISSUE TITLE
Завершить работу за коллегой

### ISSUE THREAD

**Issue by AndreiBakhtinov** [MarinaNikole/Music#67]
Разделиться на группы по два человека
1. первый имитирует коллегу, который уходит в отпуск
2. второй - завершает работу за первым

Пример именования файла
- `team1.sql`
- `team2.sql`

**Comment by antoncheprasov** [comment]
@AlexgorAlexgor я ухожу в отпуск, доделай пожалуйста файл team3.sql в ветке [cheprasov/task_products]

**Comment by AndreiBakhtinov** [comment]
Файл `team2.sql`. Ушел в отпуск. Моя ветка `show_germany_users`

**Comment by kondrashovvania** [comment]
> Файл `team2.sql`. Ушел в отпуск. Моя ветка `show_germany_users`

беру в работу

**Comment by MarinaNikole** [comment]
@MariaMarz  Мария, здравствуй. Не успеваю доделать мою работу, ухожу в отпуск. Не могла бы ты, пожалуйста, закончить это задание.

**Comment by kondrashovvania** [comment]
> Файл `team2.sql`. Ушел в отпуск. Моя ветка `show_germany_users`

задача готова

**Comment by AndreiBakhtinov** [comment]
@MarinaNikole @antoncheprasov @kondrashovvania @Zhanna-Osypenko @MariaMarz @AlexgorAlexgor 
Друзья, отличная работа!
